// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuSrhHQWYZGa0G3nyz27q-ucm_CLGaNEQ',
    appId: '1:436296011553:android:a438247c428e8cefdfb860',
    messagingSenderId: '436296011553',
    projectId: 'crud-d4421',
    databaseURL: 'https://crud-d4421-default-rtdb.firebaseio.com',
    storageBucket: 'crud-d4421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5sUU2UMdPBzelfwiN4uh7LDRPKmsc-QA',
    appId: '1:436296011553:ios:8d28fa721abda2cedfb860',
    messagingSenderId: '436296011553',
    projectId: 'crud-d4421',
    databaseURL: 'https://crud-d4421-default-rtdb.firebaseio.com',
    storageBucket: 'crud-d4421.appspot.com',
    iosClientId: '436296011553-v6vjr5ujgi1qa0eob9r4ot1sncdqet6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
